server:
  port: 8888
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.pactera.conference.pojo
spring:
  datasource:
    url: jdbc:mysql://192.168.12.5:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: templates/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
